package com.angrydu.plumbingstore.exception;

public enum ExceptionLocations {
    USER_SERVICE_NOT_FOUND,
    USER_SERVICE_VALIDATION,
    ORDER_SERVICE_VALIDATION,
    USER_DTO_ENTITY_VALIDATION,
    TOKEN_NOT_FOUND,
    TOKEN_SERVICE_VALIDATION,
    TOKEN_FORBIDDEN,
    TOKEN_SERVICE_CONFLICT,
    ORDER_SERVICE_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    MAIL_ERROR,
    KEY_ERROR;
}
